In [1]:
from environment import Environment
from magiccube import Cube
from agents import A2C, DQN, PPO
import yaml
import numpy as np
import itertools
import torch

In [2]:
args = yaml.safe_load(open("config.yaml", "r"))

env = Environment(
    method="LBL",
    size=3,
    args=args["environment"]
)

agent = DQN(env, args["DQN"])

In [3]:
cube = Cube()
print(cube)

          W  W  W                   
          W  W  W                   
          W  W  W                   
 O  O  O  G  G  G  R  R  R  B  B  B 
 O  O  O  G  G  G  R  R  R  B  B  B 
 O  O  O  G  G  G  R  R  R  B  B  B 
          Y  Y  Y                   
          Y  Y  Y                   
          Y  Y  Y                   



In [ ]:
env.scramble()
print(env.state2)
print(env.state2.shape)

[[[ 3  4  1  0  0]
  [ 2  5 -1  1 16]
  [ 0  2  5  2 25]
  [ 1 -1  3  3  1]
  [ 1 -1 -1  4  4]
  [ 0 -1  5  5 22]
  [ 1  5  2  6  8]
  [ 1  2 -1  7  7]
  [ 1  4  2  8  6]
  [-1  3  4  9  9]
  [-1  3 -1 10 10]
  [-1  0  2 11 24]
  [-1 -1  4 12 12]
  [-1 -1  5 13 13]
  [-1  5  1 14  5]
  [-1  2 -1 15 15]
  [-1  0  3 16 18]
  [ 5  1  3 17  2]
  [ 0  4 -1 18 20]
  [ 0  2  4 19 23]
  [ 4 -1  2 20 14]
  [ 0 -1 -1 21 21]
  [ 1 -1  4 22  3]
  [ 3  5  0 23 19]
  [ 3  5 -1 24 11]
  [ 0  3  4 25 17]]]


In [4]:
import torch
import torch.nn as nn

In [5]:
# Definiamo un layer lineare: input con 3 feature, output con 2 feature
fc1 = nn.Linear(in_features=3, out_features=256)
fc2 = nn.Linear(in_features=256, out_features=2)

# Esempio di input: batch di 4 esempi, ciascuno con 3 feature
input_matrix = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0],
    [10.0, 11.0, 12.0]
])  # shape: (4, 3)

# Passaggio della matrice al layer
output = fc1(input_matrix)
print(output)
output = fc2(output)

print("Output:", output)

tensor([[ 0.4779, -0.3759,  0.7937,  ..., -0.5165,  0.2668, -0.6472],
        [ 1.9035,  0.3834,  1.0553,  ..., -1.0488,  0.5531, -0.7500],
        [ 3.3291,  1.1427,  1.3170,  ..., -1.5811,  0.8395, -0.8528],
        [ 4.7547,  1.9020,  1.5787,  ..., -2.1135,  1.1258, -0.9556]],
       grad_fn=<AddmmBackward0>)
Output: tensor([[ 1.2043, -0.8222],
        [ 3.7111, -2.4189],
        [ 6.2179, -4.0155],
        [ 8.7247, -5.6122]], grad_fn=<AddmmBackward0>)
