In [77]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [78]:
color = {
    "U": 0,
    "D": 1,
    "F": 2,
    "R": 3,
    "B": 4,
    "L": 5
}

In [79]:
state = "UUUUUUUUURRRRRRRRRFFFFFFFFFDDDDDDDDDLLLLLLLLLBBBBBBBBB"
state_for_tensor = []
for s in state:
    state_for_tensor.append(color[s])

state_for_tensor

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4]

In [80]:
x = torch.tensor(state_for_tensor, dtype=torch.float)

In [81]:
class Net(nn.Module):
    def __init__(self, input_dim, n_actions):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, 128)
        self.fc2 = nn.Linear(128, 256)
        self.fc3 = nn.Linear(256, 256)
        self.fc4 = nn.Linear(256, 128)
        self.fc5 = nn.Linear(128, n_actions)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = self.fc5(x)

        return x
    
model = Net(54, 12)

In [ ]:
move = model.forward(x)
argmax = move.argmax().item()


print(move, argmax)

tensor([-0.0509, -0.0298,  0.0529, -0.1278, -0.0813,  0.0431,  0.0202, -0.0558,
         0.0237,  0.0224, -0.1628,  0.1347], grad_fn=<ViewBackward0>) 11


In [ ]:
import time

device = "cuda"
model.to(device)
x.to(device)

while True:
    model = Net(54, 18)
    move = model.forward(x)
    argmax = move.max(0).indices.view(1, 1)

    print(argmax)
    #time.sleep(5)

tensor([-0.0671,  0.0032, -0.0332,  0.0961,  0.0386,  0.0161, -0.0449, -0.1385,
         0.0570,  0.0795, -0.1326, -0.0937,  0.0611,  0.1390, -0.1163, -0.0100,
        -0.0665,  0.1102], grad_fn=<ViewBackward0>)
tensor([-0.1142,  0.0352, -0.0295, -0.0028, -0.0968, -0.0082,  0.0665,  0.0497,
         0.0055, -0.0166,  0.1438, -0.0627,  0.0370,  0.0246, -0.1412, -0.0624,
        -0.0933,  0.0046], grad_fn=<ViewBackward0>)
tensor([ 0.0235, -0.0779, -0.0617, -0.0878, -0.0529, -0.0222, -0.0272, -0.0852,
        -0.0492,  0.1057, -0.1760, -0.0140,  0.0315,  0.0514,  0.0171,  0.1423,
         0.0175,  0.0378], grad_fn=<ViewBackward0>)
tensor([-0.0162,  0.0099, -0.0686, -0.0775,  0.0420, -0.0730,  0.0643, -0.0714,
         0.1344,  0.0294, -0.0552, -0.1044,  0.0286,  0.0385, -0.0197,  0.0026,
         0.0873, -0.0224], grad_fn=<ViewBackward0>)
tensor([-0.0091, -0.0678,  0.0271,  0.0734,  0.0164, -0.0853, -0.0222, -0.0738,
         0.2611,  0.0770, -0.0131, -0.0788,  0.0549, -0.0461, -0.0644,  

KeyboardInterrupt: 